language: python
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database dashboard;' -U postgres
#- psql -c "create user dashboard_user with password '123';" -U postgres
- cp dashboard/travissettings.py dashboard/settings.py
script:
- python manage.py makemigrations
- python manage.py migrate
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: fyCkVcpYAbAAghkFpWc1Ct5zbcf+X0W7uTVKQiAn+CSxYwRg8sjOrco4anMm9Udk+RkjppUGhFqqXaw2CRFMa935bYqJuDBj6wtdTwIvolZonQErf+ionBu8ewYDzyEiuWTe3Fw6v4dehK6vOV5+Zm+7SW75zoK7OyKWRwkVFHqzAapAoosTOUQJWLD+MAdMciizBp/5eoV69L2r45qjGQeiGM64GQMMPoffnXbdLCcIsA/heGixH9lCNGqkkFmukhhu3fYwBKAeJoMJdb4U2RjHItyAQU5xUHyhnuO1XGNtmhzFlsMSorMsRVQWBRX2zfLZ/5f0o7hM3EkNwVq3ErVGfb8WwYOCqHUMqDCLBUg+t1DUK6OaOu9oxVTPLd01mkK2Jbl/MJEeqdQqmtelfHfQPweA6uauwjQxAygd35gF4QSDr/ltRZJqnL3pjDVAY9N+tRytBhHTqf3isZhpUCE1PUc8NFxQ2yTOblYSzvwVuNQQNwnTfmkiRMHBrOFQka0xhYNzPaGfVwCVkT63m4xySKwil8hXS2YFyGfxONuXYTM/NemdUrOIDSzYkRw6Nm53L7f3D557Jbw7AUKH8BpORoY1aIUEDbwBRx45zXEBEBsqnGWAzXu03yFZTgfcSTO8fwHLFNY8N27GwuEvLEU9heVHbKJZ/gqcgWzWsrQ=
  app: wildcard-boiz
  on:
    repo: uva-cs3240-s20/project-wildcard