# Generated by Django 3.0.2 on 2020-03-29 06:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=-1)),
                ('task_name', models.CharField(max_length=200)),
                ('task_desc', models.CharField(max_length=400)),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('length', models.DurationField(default=datetime.timedelta(days=3))),
                ('completed', models.BooleanField(verbose_name='completed')),
                ('link', models.URLField(default='')),
                ('category', models.CharField(blank=True, choices=[('hw', 'Homework'), ('chore', 'Chore'), ('work', 'Work'), ('errand', 'Errand'), ('life', 'Lifestyle'), ('others', 'Others')], max_length=32, null=True)),
            ],
        ),
    ]
