# Generated by Django 3.0.3 on 2020-04-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showarchived',
            name='id',
        ),
        migrations.AlterField(
            model_name='showarchived',
            name='user',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
    ]
