# Generated by Django 3.0.4 on 2020-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Homework', 'Homework'), ('Chore', 'Chore'), ('Work', 'Work'), ('Errand', 'Errand'), ('Life', 'Lifestyle'), ('Other', 'Others')], max_length=32, null=True),
        ),
    ]
