# Generated by Django 3.0.2 on 2020-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('hw', 'Homework'), ('chore', 'Chore'), ('work', 'Work'), ('errand', 'Errand'), ('life', 'Lifestyle')], max_length=20, null=True),
        ),
    ]
