# Generated by Django 3.0.3 on 2020-04-05 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='length',
            field=models.DurationField(default=datetime.timedelta(seconds=10800), verbose_name='length'),
        ),
    ]
