# Generated by Django 3.0.2 on 2020-03-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='link',
        ),
    ]
