# Generated by Django 3.0.3 on 2020-04-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours',
            field=models.IntegerField(default=2, verbose_name='hours'),
        ),
        migrations.AddField(
            model_name='task',
            name='minutes',
            field=models.IntegerField(default=0, verbose_name='minutes'),
        ),
    ]
