# Generated by Django 3.0.3 on 2020-03-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.IntegerField(default=-1),
        ),
    ]
