# Generated by Django 3.0.3 on 2020-04-07 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200407_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='length',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=10800), null=True, verbose_name='length'),
        ),
    ]
