# Generated by Django 3.0.2 on 2020-03-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category'),
        ('tasks', '0005_task_user'),
    ]

    operations = [
    ]
