# Generated by Django 3.0.3 on 2020-03-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200320_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('Homework', 'Homework'), ('Chore', 'Chore'), ('Work', 'Work'), ('Errand', 'Errand'), ('Life', 'Lifestyle'), ('Other', 'Others')], max_length=32, null=True),
        ),
    ]
