# Generated by Django 3.0.3 on 2020-03-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200330_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='archived'),
        ),
    ]
