# Generated by Django 3.0.2 on 2020-04-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
    ]
