# Generated by Django 3.0.3 on 2020-04-01 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
    ]
