# Generated by Django 3.0.3 on 2020-04-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateField(null=True, verbose_name='date_completed'),
        ),
    ]
